console_title_template = '{{.UserName}}@{{.HostName}} in {{.PWD}}'
version = 4
final_space = true

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = true

[maps]
[maps.host_name]
Yovkos-MacBook-Air = "MBA"

#[maps.user_name]
#root = "üöÄ"
#yovko = "‚ö°"

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = ' {{ if .WSL }}WSL at {{ end }}{{.Icon}} '
    leading_diamond = '‚ï≠‚îÄÓÇ≤'
    foreground = '#000000'
    background = '#d3d7cf'
    type = 'os'
    style = 'diamond'

  [[blocks.segments]]
    template = ' ÔÅº {{ .Path }} '
    foreground = '#e4e4e4'
    powerline_symbol = 'ÓÇ∞'
    background = '#3465a4'
    type = 'path'
    style = 'powerline'

    [blocks.segments.options]
      home_icon = '~'
      style = 'full'

#    [blocks.segments.options.mapped_locations]
#      "~/Developer" = "Û∞≤ã"
#      "~/Documents" = "Û∞àô"
#      "~/Downloads" = "ÔÄô"
#      "~/Music" = "Û∞ùö"
#      "~/Pictures" = "ÔÄæ"

  [[blocks.segments]]
    template = ' {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} ÔÅÑ {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} ÔÅÜ {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} Ó≠ã {{ .StashCount }}{{ end }} '
    foreground = '#000000'
    powerline_symbol = 'ÓÇ∞'
    background = '#8bc34a'
    type = 'git'
    style = 'powerline'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#fdd835{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#f26d50{{ end }}', '{{ if gt .Ahead 0 }}#89d1dc{{ end }}', '{{ if gt .Behind 0 }}#4e9a06{{ end }}']

    [blocks.segments.options]
      branch_icon = 'ÔÑ¶ '
      fetch_status = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    template = 'Óúò:{{ .Major }} {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }}{{ end }}'
    foreground = '#8bc34a'
    type = 'node'

    [blocks.segments.options]
      fetch_version = true

  [[blocks.segments]]
    template = 'Óòß:{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
    foreground = '#26c6da'
    type = 'go'

    [blocks.segments.options]
      fetch_version = true

  [[blocks.segments]]
    template = 'Óû®:{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
    foreground = '#c62828'
    type = 'rust'

    [blocks.segments.options]
      fetch_version = true

  [[blocks.segments]]
    template = 'Óàµ:{{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}'
    foreground = '#111111'
    type = 'python'

    [blocks.segments.options]
      display_mode = 'files'
      fetch_virtual_env = true

  [[blocks.segments]]
    template = 'Ôâ∞:{{ .Profile }}'
    foreground = '#ff5722'
    type = 'aws'
    background_templates = ['{{if contains "default" .Profile}}#FFA400{{end}}', '{{if contains "yovko" .Profile}}#f1184c{{end}}']

    [blocks.segments.options]
      display_default = false

  [[blocks.segments]]
    template = "Ôåà:{{ .Context }} "
    foreground = "#0b59e7"
    type = "docker"

  [[blocks.segments]]
    template = 'Ôåà:{{.Context}}::{{if .Namespace}}{{.Namespace}}{{else}}default{{end}} '
    foreground = '#eeeeee'
    type = 'kubectl'

  [[blocks.segments]]
    template = ' {{ .FormattedMs }} Ôâí '
    foreground = '#fdd835'
    type = 'executiontime'

    [blocks.segments.options]
      style = 'round'

  [[blocks.segments]]
    template = ' {{ if gt .Code 0 }}‚úò{{ else }}‚úî{{ end }} '
    foreground = '#7cb342'
    foreground_templates = ['{{ if gt .Code 0 }}#f44336{{ end }}']
    type = 'status'

    [blocks.segments.options]
      always_enabled = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '‚ï∞‚îÄ {{ if .Root }}#{{else}}${{end}}'
    foreground = '#d3d7cf'
    type = 'text'
    style = 'plain'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}green{{end}}",
  ]
  background = 'transparent'
  template = '‚ùØ '
